# Generated by Django 5.2 on 2025-04-23 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6085a912-bd3a-4455-b87a-9576e9359729'), editable=False, primary_key=True, serialize=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6085a912-bd3a-4455-b87a-9576e9359729'), editable=False, primary_key=True, serialize=False),
        ),
    ]
