# Generated by Django 5.2 on 2025-04-23 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_language_id_alter_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d771fe2b-8a40-447b-b8fb-3b1458f9c6c9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d771fe2b-8a40-447b-b8fb-3b1458f9c6c9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='users.language'),
        ),
    ]
