# Generated by Django 5.2 on 2025-04-24 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_language_id_alter_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30cf364c-e7a3-473a-8de8-25865ad6b7fb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30cf364c-e7a3-473a-8de8-25865ad6b7fb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
