# Generated by Django 5.2 on 2025-04-25 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_language_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3da2829-3266-459f-9837-b657adec2667'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3da2829-3266-459f-9837-b657adec2667'), editable=False, primary_key=True, serialize=False),
        ),
    ]
