# Generated by Django 3.2 on 2025-04-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('users', '0010_alter_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Account Object object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Customer Object object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
    ]
