# Generated by Django 3.2 on 2025-04-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_workoutplan_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='is_purchasable',
            new_name='is_purchased',
        ),
    ]
