# Generated by Django 3.2 on 2025-04-30 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_remove_workoutplan_is_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
